sudo: false
language: java
jdk:
  - oraclejdk8

# http://binkley.blogspot.com/2015/10/struggling-with-travis-ci-and-maven-33.html
# https://github.com/travis-ci/travis-ci/issues/3778
before_install:
  - wget http://mirrors.ocf.berkeley.edu/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar zxvf apache-maven-3.3.9-bin.tar.gz
  - chmod +x apache-maven-3.3.9/bin/mvn
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r
before_script:
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r

script: mvn clean verify
